version: "3.7"

services:
  app:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - TZ=Asia/Shanghai
  redis:
    image: redis:5.0.13
    volumes:
      - redis:/data
    environment:
      - TZ=Asia/Shanghai
  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod
    volumes:
      - "/data/mongo:/data/db"
      - "/data/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    environment:
      - TZ=Asia/Shanghai
volumes:
  redis:
